FROM node:18 AS builder

# Create app directory
WORKDIR /app



# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/

RUN npm install prisma --save-dev


COPY . .
# Install app dependencies
RUN npm install --include=dev

RUN npm install -g @nestjs/cli


# Generate prisma client, leave out if generating in `postinstall` script
RUN npx prisma generate


EXPOSE 8000
CMD ["npm", "run", "dev"]
